id: P000730
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:39:26.648646
source_metadata:
  id: bdr:W4PD1211
  title: ཁྲིད་ཡིག་ཡེ་ཤེས་བླ་མ་མཆན་ཅན།
  author: ''
  volumes:
    b13d4c450652488096d50d4ec2cc7a07:
      image_group_id: I4PD1446
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
