id: I6021FFF0
legacy_id: P000730
ocr_import_info:
  bdrc_scan_id: W4PD1211
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T03:07:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:15:46.512425+00:00'
last_modified: 2022-09-04 05:15:55.314563
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD1211
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD1211
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁྲིད་ཡིག་ཡེ་ཤེས་བླ་མ་མཆན་ཅན།
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6988767370124087
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I4PD1446:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD1446
      total_pages: 294
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD1446.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.6988767370124087
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
