id: I6021FFF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:09:52+00:00'
last_modified: '2022-06-07T13:35:07.263127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD1211
  title: ཁྲིད་ཡིག་ཡེ་ཤེས་བླ་མ་མཆན་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D277:
      image_group_id: I4PD1446
      title: ''
      total_pages: 294
      order: 1
      base_file: D277.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
